name: Chocolatine
on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'
env:
  EXECUTABLES: 'chocolatine'
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-LIL-2-1-chocolatine-martin.delebecque.git"
jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
    - uses: actions/checkout@v4
    - name: Check coding style
      run: |
          check.sh $(pwd) $(pwd)
          while IFS=: read -r file line type msg; do
            echo "::error file=${file#./},line=$line,title=$type::$msg"
          done < $(pwd)/coding-style-reports.log
          if [ -s $(pwd)/coding-style-reports.log ]; then
            exit 1
          else
            echo "No coding style errors detected"
          fi
  check_program_compilation:
    needs: check_coding_style
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v4
    - name: Compile program
      run: |
        make
        make clean
    - name: Check executables
      run: |
        for file in ${{ env.EXECUTABLES }}; do
          if [ ! -x "${{ env.EXECUTABLES }}" ]; then
            echo "Executable $file not found or not executable"
            exit 1
          fi
        done

  run_tests:
    needs: check_program_compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        make tests_run
  push_to_mirror:
      runs-on: ubuntu-latest
      needs: [check_program_compilation, check_coding_style, run_tests]
      steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - name: Push Epitech
            uses: pixta-dev/repository-mirroring-action@v1
            with:
              target_repo_url:
                ${{ env.MIRROR_URL }}
              ssh_private_key:
                ${{ secrets.GIT_SSH_PRIVATE_KEY }}