name: Repository size

on:
  push:
jobs:
  repo_size:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: repo_size
      run: |
        echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)"
        du -skh --exclude=".git" 
